'use client';
import React,{useState} from 'react';
import InvitationPreview,{InviteData} from '../components/InvitationPreview';
const empty:InviteData={bride:'',groom:'',date:'',time:'',venue:'',bridePhoto:'',groomPhoto:'',card:''};
function readFile(file:File,setter:(v:string)=>void){const r=new FileReader();r.onload=()=>setter(String(r.result));r.readAsDataURL(file)}
export default function Home(){const [d,setD]=useState<InviteData>(empty);const [msg,setMsg]=useState('');
 const update=(k:keyof InviteData,v:string)=>setD(x=>({...x,[k]:v}));
 const submit=(e:React.FormEvent)=>e.preventDefault();
 const exportPreview=()=>{window.print()};
 return <main className="page"><header className="header"><div><div className="brand">YUVI STUDIO</div><div className="sub">Wedding E-Invitation Creator</div></div><div className="sub">9:16 • Mobile First</div></header><div className="grid"><section className="panel"><h1 className="title">Create Wedding Invitation</h1><p className="muted">Upload photos and enter the wedding details. Preview instantly.</p><form onSubmit={submit}><div className="fields"><div className="field"><label>Groom Name</label><input value={d.groom} onChange={e=>update('groom',e.target.value)} placeholder="Yuvaraj"/></div><div className="field"><label>Bride Name</label><input value={d.bride} onChange={e=>update('bride',e.target.value)} placeholder="Anitha"/></div><div className="field"><label>Wedding Date</label><input value={d.date} onChange={e=>update('date',e.target.value)} placeholder="16 September 2026"/></div><div className="field"><label>Wedding Time</label><input value={d.time} onChange={e=>update('time',e.target.value)} placeholder="11:00 AM"/></div><div className="field full"><label>Venue</label><input value={d.venue} onChange={e=>update('venue',e.target.value)} placeholder="MGR Mandapam, Pothanur"/></div><div className="field"><label>Groom Photo</label><div className="upload"><input type="file" accept="image/*" onChange={e=>e.target.files&&e.target.files[0]&&readFile(e.target.files[0],v=>update('groomPhoto',v))}/></div></div><div className="field"><label>Bride Photo</label><div className="upload"><input type="file" accept="image/*" onChange={e=>e.target.files&&e.target.files[0]&&readFile(e.target.files[0],v=>update('bridePhoto',v))}/></div></div><div className="field full"><label>Invitation Card (optional)</label><div className="upload"><input type="file" accept="image/*" onChange={e=>e.target.files&&e.target.files[0]&&readFile(e.target.files[0],v=>update('card',v))}/></div></div></div><div className="actions"><button className="btn primary" type="button" onClick={exportPreview}>Export Preview</button><button className="btn secondary" type="button" onClick={()=>{setD(empty);setMsg('Cleared')}}>Reset</button></div>{msg&&<p className="muted">{msg}</p>}</form></section><section className="panel"><h2 className="title" style={{fontSize:20}}>Live Preview</h2><p className="muted">This is the first cinematic scene. The full MP4 renderer can be connected with Remotion.</p><InvitationPreview data={d}/></section></div></main>}
